//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagePatch
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> BooksId { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
